version: "3.1"

services:
  mongo:
    image: mongo
    networks:
      - mongo_network
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data1:/data/db

  mongo-client:
    image: mongo
    networks:
      - mongo_network
    restart: always
    volumes:
      - mongodb_data2:/data/db

volumes:
  mongodb_data1:
  mongodb_data2:

networks:
  mongo_network: